apiVersion: apps/v1
kind: Deployment
metadata:
  name: kodecamp-devops-bootcamp-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kodecamp-devops-bootcamp-app
  template:
    metadata:
      labels:
        app: kodecamp-devops-bootcamp-app
    spec:
      containers:
      - name: kodecamp-devops-bootcamp-app
        image: actokuyt/certified-devops-app:latest
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
