name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  terraform-provision:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0 

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1 
          
      - name: Write SSH private key to file
        run: |
          echo "${{ secrets.SSH_KEY }}" > private_key.pem
          chmod 600 private_key.pem
        working-directory: terraform
        
      - name: Terraform Init
        run: terraform init
        working-directory: terraform
    
      - name: Terraform Apply
        run: terraform apply -auto-approve -var="private_key_path=private_key.pem"
        working-directory: terraform

      - name: Capture EC2 Public IP
        id: ec2_output
        run: echo $(terraform output -raw ec2_public_ip) >> ec2ip.txt
        working-directory: terraform

      - name: Save EC2 Public IP as artifact
        uses: actions/upload-artifact@v3
        with:
          name: ec2-public-ip
          path: terraform/ec2ip.txt

  docker-containerize:
    needs: terraform-provision
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build and push Docker image
        run: |
          docker build -t actokuyt/certified-devops-app .
          docker push actokuyt/certified-devops-app

  minikube-deploy:
    needs: docker-containerize
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download EC2 Public IP artifact
        uses: actions/download-artifact@v3
        with:
          name: ec2-public-ip

      - name: Load EC2 Public IP
        id: load_ip
        run: |
          EC2_PUBLIC_IP=$(cat ec2ip.txt)
          echo "EC2_PUBLIC_IP=$EC2_PUBLIC_IP" >> $GITHUB_ENV

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Deploy to Minikube
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@$EC2_PUBLIC_IP << 'EOF'
            minikube start
            kubectl apply -f /home/ubuntu/app/deployment.yaml
            kubectl apply -f /home/ubuntu/app/service.yaml
          EOF
