name: Deploy to Minikube

on:
  workflow_run:
    workflows: ["Terraform AWS Provisioning"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build and push Docker image
        run: |
          docker build -t actokuyt/certified-devops-app .
          docker push actokuyt/certified-devops-app

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download EC2 Public IP artifact
        uses: actions/download-artifact@v3
        with:
          name: ec2-public-ip

      - name: Load EC2 Public IP
        run: |
          source ec2ip.txt

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Deploy to Minikube
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@$EC2_PUBLIC_IP << 'EOF'
            minikube start
            kubectl apply -f /home/ubuntu/app/deployment.yaml
            kubectl apply -f /home/ubuntu/app/service.yaml