name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  docker-containerize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build and push Docker image
        run: |
          docker build -t actokuyt/certified-devops-app .
          docker push actokuyt/certified-devops-app

  minikube-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: SSH into EC2 and deploy to Minikube
      uses: appleboy/ssh-action@v0.1.1
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.SSH_KEY }}
        script: |
          kubectl apply -f ~/path/to/k8s/deployment.yaml
          kubectl apply -f ~/path/to/k8s/service.yaml

