name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  docker-containerize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build and push Docker image
        run: |
          docker build -t actokuyt/certified-devops-app .
          docker push actokuyt/certified-devops-app

  # minikube-deploy:
  #   needs: docker-containerize
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2
        
  #     - name: Set up SSH
  #       uses: webfactory/ssh-agent@v0.5.3
  #       with:
  #         ssh-private-key: ${{ secrets.SSH_KEY }}

  #     - name: Deploy to Minikube
  #       run: |
  #           ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
  #               minikube start
  #               kubectl apply -f /home/ubuntu/app/deployment.yaml
  #               kubectl apply -f /home/ubuntu/app/service.yaml
  #           EOF
